[package]
name = "xt_app"
version = "0.1.0"
edition = "2021"
license.workspace = true
default-run = "xt_app"

[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
rfd = { version = "0.14", default-features = false, features = ["xdg-portal", "async-std"] }
xt_core = { path = "../xt_core" }
